### ISSUE TITLE
How-to `depend: standard-library` ?

### ISSUE THREAD

**Issue by andreasabel** [wenkokke/setup-agda#84] opened 2022-11-12 07:41 UTC
@wenkokke I tried this action and was amazed how blazingly fast it installs Agda: 8s over 30min with `stack install Agda`!

How can I install the standard library with your action such that it is found when my project has `depend: standard-library` in its `.agda-lib` file?  It seems that the std-lib is always set up with a version suffix...

Re: https://github.com/andreasabel/ipl/actions/workflows/kokke-ci.yml

**Comment by wenkokke** [comment] 2022-11-12 14:18
See: https://github.com/wenkokke/setup-agda/blob/9115cb2cfe6562419d8db46392c6ae0db663c1c7/action.yml#L12-L26

**Comment by andreasabel** [comment] 2022-11-12 17:33
Yes I read this through, but neither `1.7.1` nor `recommended` made the standard library available in a form that it would be picked up via `depend: standard-library` (without suffix):
- `recommended`: cannot find module `Size`: https://github.com/andreasabel/ipl/actions/runs/3446608914/jobs/5751725765
- `1.7.1` and `...-default: true`: cannot find library `standard-library`: https://github.com/andreasabel/ipl/actions/runs/3446580716/jobs/5751661050
- `1.7.1`: cannot find module `Size`: https://github.com/andreasabel/ipl/actions/runs/3446501617/workflow

**Comment by wenkokke** [comment] 2022-11-12 21:46
Strange! This works for Schmitty.

**Comment by wenkokke** [comment] 2022-11-12 21:48
This is probably due to the fact that I don't understand the ad-hoc versioning mechanism?

**Comment by wenkokke** [comment] 2022-11-13 00:58
@andreasabel I can reproduce *some* problem:

https://github.com/wenkokke/setup-agda/actions/runs/3453227059/jobs/5763664685#step:5:12

```
Checking Everything (/home/runner/work/setup-agda/setup-agda/andreasabel/ipl/src/Everything.agda).
 Checking Library (/home/runner/work/setup-agda/setup-agda/andreasabel/ipl/src/Library.agda).
  Checking Size (/home/runner/.agda/libraries.d/standard-library/1.7.1/src/Size.agda).
   Checking Level (/home/runner/.agda/libraries.d/standard-library/1.7.1/src/Level.agda).
/home/runner/work/setup-agda/setup-agda/andreasabel/ipl/src/Library.agda:8,1-32
Importing module Size using the --sized-types flag from a module
which does not.
when scope checking the declaration
  open import Size public
```

**Comment by wenkokke** [comment] 2022-11-14 00:58
Could you try setting the `working-directory`? Is Agda picking up the .agda-lib file?

**Comment by andreasabel** [comment] 2022-11-14 07:37
> Is Agda picking up the `.agda-lib` file?

This seems to be the problem, although I do not understand why Agda does not do it.

> Could you try setting the `working-directory`? 

Using `working-directory: foo` instead of `-i foo` and `foo/Everything.agda` seems to do the trick: https://github.com/andreasabel/ipl/actions/runs/3459378147/jobs/5774715567

Great, thanks! 
So the problem is on the Agda side of things...

**Comment by andreasabel** [comment] 2022-11-14 07:47
With `standard-library-default: true` I previously got this error, see https://github.com/andreasabel/ipl/actions/runs/3446580716/jobs/5751661050:
```
Run agda -i src src/Everything.agda --html
 Library 'standard-library.agda-lib' not found.
 Add the path to its .agda-lib file to
   '/home/runner/.agda/libraries'
 to install.
 Installed libraries:
   standard-library-1.7.1
     (/home/runner/.agda/libraries.d/standard-library/1.7.1/standard-library.agda-lib)
```
This error is quite paradoxical, I'd like to understand what goes wrong here. Personally, I never use the `~/.agda/defaults` file, so I do not experience this problem locally.  

What does the action write into the `defaults` file?  I would guess it puts `standard-library` there.  
Maybe Agda's default library mechanism does not cope with versioning?

**Comment by wenkokke** [comment] 2022-11-14 21:45
Closing this as solved, but will reopen an issue to investigate the defaults issue.

**Closed by wenkokke** 2022-11-14 21:45 UTC
Labels: bug
